name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"

      - name: flake8 Linter
        run: pip install flake8 && flake8 --statistics --count --ignore=E501
      
      - name: Run tests
        run: python3 test_random_strings.py
